### ISSUE TITLE
Support multiple certificates and other enhancement in TokenGenerator

### ISSUE THREAD

**Issue by taojing2002** [DataONEorg/d1_portal#4]
Currently the TokenGenerator class only supports one `private key`/`public certificate` to issue/verify tokens.

For the verifying process, we want it smarter so it can choose a certificate based on the issuer to verify token. That makes the class verify tokens issued by different authorities. 

Do we need to make the library issue tokens from different authorities (private keys) as well? If we do, I think it has lower priority thank verifying.

This class has another issue - it fetches certificate from the cn url every time when it verifies a token. We need a cache mechanism to eliminate those unnecessary network traffics. Since the cn LE certificate expires every three months, the cache mechanism should  handle the case either by periodically checking or refetching after a failure.

**Comment by taojing2002** [comment]
This the [code](https://github.com/DataONEorg/d1_portal/blob/master/src/main/java/org/dataone/portal/TokenGenerator.java) of the class in the main branch.

**Comment by artntek** [comment]
Forgot to address these:

> Do we need to make the library issue tokens from different authorities (private keys) as well? If we do, I think it has lower priority thank verifying.

I agree this is a lower priority (if it is even necessary at all), so we should punt for now.


> This class has another issue - it fetches certificate from the cn url every time when it verifies a token. We need a cache mechanism to eliminate those unnecessary network traffics. Since the cn LE certificate expires every three months, the cache mechanism should handle the case either by periodically checking or refetching after a failure.

The existing code does actually cache the server cert, and does not re-fetch for every request. There is also a check every 5 minutes to ensure the cached copy is still valid, and finally, in case of a failure, the certificate is re-fetched.
